Plan-GKE_job:
  stage: plan
  extends: .plan_template
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: manual
      changes:
        - "google/devops-workshop-2023/gke/*.tf"
  variables:
    TF_DIR: "./google/devops-workshop-2023/gke"

Apply-GKE_job:
  stage: apply
  extends: .apply_template
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      when: manual
      changes:
        - "google/devops-workshop-2023/gke/*.tf"
      allow_failure: false
  variables:
    TF_DIR: "./google/devops-workshop-2023/gke"
